version: "3.3"
services:
  front:
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
    container_name: hackTestFront
    ports:
      - 3000:3000
    restart: always